version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
